### ISSUE TITLE
Composer fails to install php-tupas

### ISSUE THREAD

**Issue by phuwin1995** [tuutti/php-tupas#9]
I downloaded the repo. Run this: `composer require tuutti/php-tupas` but I am unable to install.
```
Using version dev-master for tuutti/php-tupas
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
**Your requirements could not be resolved to an installable set of packages.**

  Problem 1
    - The requested package tuutti/php-tupas No version set (parsed as 1.0.0) is satisfiable by tuutti/php-tupas[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.


**Installation failed, reverting ./composer.json to its original content.**
```

**Comment by bartfeenstra** [comment]
Hi there! You're getting this error because there is no stable release yet, but your application does not allow unstable releases. This is a an issue with how you use Composer, and not with Composer or this package itself. See https://getcomposer.org/doc/04-schema.md#minimum-stability for more details on how to control this behavior for your applications.

**Comment by phuwin1995** [comment]
Hi,

Thanks for the quick reply. I am new to composer. I have managed to install using `composer require "tuutti/php-tupas @dev"`.

Cheers!
